baseURL = 'https://example.org/'
languageCode = 'pt-br'
title = 'Blog do Samuel'
theme = 'hugo-flex'

[params]
    footer = '<a href="github.com/DavdSamuel">Meu GitHub</a> | Quer enviar sugestões? Me mande um e-mail: <a href="mailto:samuelmarinhodasilvamarinho@gmail.com">samuelmarinhodasilvamarinho@gmail.com</a>'